/*
 * This file is part of weblivegraphics.
 *
 * weblivegraphics is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * any later version.
 *
 * weblivegraphics is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * Copyright (C) Media ex Machina 2021
 *
 */
package media.mexm.weblivegraphics;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Properties;

import org.apache.commons.io.FileUtils;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

public class VendorSetup {
	private static final Logger log = LogManager.getLogger();

	private final Properties internal;

	public VendorSetup(final File propertyFile) throws IOException {
		internal = new Properties();
		if (propertyFile.exists() == false) {
			FileUtils.createParentDirectories(propertyFile);
			try (var fos = new FileOutputStream(propertyFile)) {
				internal.store(fos,
				        "Automatic generated by weblivegraphics. Never share or commit this file: it can contain secrets keys!");
			}
			log.warn("No vendor propertyFile set. Create one on {}, please setup it.", propertyFile);
		} else {
			log.debug("Load vendor propertyFile: {}", propertyFile);
			try (var fis = new FileInputStream(propertyFile)) {
				internal.load(fis);
			}
		}
	}

}
