# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Javascript CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  sonarcloud:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
        args: >
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=mediaexmachina
          -Dsonar.projectKey=mediaexmachina_weblivegraphics
          -Dsonar.verbose=true
          -Dsonar.login=$SONAR_TOKEN
          -Dsonar.sources="src/main/js"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

#           -Dsonar.python.coverage.reportPaths=coverage.xml
#           -Dsonar.sources=src/main/js
#           -Dsonar.test.exclusions=tests/**
#           -Dsonar.tests=tests/
# projectBaseDir: src/main/js

